version: '3.2'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING.DATASOURCE.URL: jdbc:h2:mem:testdb
      SPRING.DATASOURCE.USERNAME: sa
      SPRING.DATASOURCE.PASSWORD:
      SPRING.H2.CONSOLE.ENABLED: 1
      SPRING.H2.CONSOLE.PATH: /h2-console

      SPRING.JPA.SHOW-SQL: 0
      SPRING.JPA.PROPERTIES.HIBERNATE.FORMAT_SQL: 1
      SPRING.JPA.HIBERNATE.DDL-AUTO: update

      SPRING.KAFKA.BOOTSTRAP-SERVERS: kafka:9092
      SPRING.KAFKA.CONSUMER.GROUP-ID: my-group
      SPRING.KAFKA.CONSUMER.MAX-POLL-RECORDS: 200
      SPRING.KAFKA.CONSUMER.ENABLE-AUTO-COMMIT: 0
      SPRING.KAFKA.CONSUMER.AUTO-OFFSET-RESET: latest
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper